services:
  - type: web
    name: microblog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: FLASK_APP
        value: PY2.py
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production